name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  PYTHON_ROOT: './backend'
  NODE_ROOT: './frontend'
  # Test Configuration
  COVERAGE_THRESHOLD: 80
  PYTEST_ADDOPTS: '--color=yes'
  # Environment Detection
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/develop' && 'staging' || 'development' }}

jobs:
  backend-lint:
    name: Backend Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PYTHON_ROOT }}
    env:
      DATABASE_URL: sqlite:///./dev.db
      TEST_DATABASE_URL: sqlite:///./test.db
      SECRET_KEY: ${{ secrets.SECRET_KEY || 'dev-secret-key-123' }}
      CORS_ORIGINS: ${{ secrets.CORS_ORIGINS || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        id: install
        run: |
          echo "::group::Upgrade pip"
          python -m pip install --upgrade pip
          echo "::endgroup::"

          echo "::group::Install project dependencies"
          pip install -r requirements.txt
          echo "::endgroup::"

          echo "::group::Install dev dependencies"
          pip install -r requirements-dev.txt
          echo "::endgroup::"

      - name: Run linting
        if: success() || failure()  # Run even if install step fails
        run: |
          echo "::group::Running Black formatter check"
          python -m black . --check || echo "::warning::Black formatting issues found"
          echo "::endgroup::"

          echo "::group::Running Flake8"
          python -m flake8 . || echo "::warning::Flake8 issues found"
          echo "::endgroup::"

          echo "::group::Running MyPy"
          python -m mypy . || echo "::warning::Type checking issues found"
          echo "::endgroup::"

  backend-test:
    name: Backend Tests
    needs: backend-lint
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./test.db
      TEST_DATABASE_URL: sqlite:///./test.db
      SECRET_KEY: ${{ secrets.SECRET_KEY || 'test-secret-key-123' }}
      CORS_ORIGINS: http://localhost:3000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            ${{ env.PYTHON_ROOT }}/requirements.txt
            ${{ env.PYTHON_ROOT }}/requirements-dev.txt

      - name: Install dependencies
        id: install
        working-directory: ${{ env.PYTHON_ROOT }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests
        id: tests
        env:
          COVERAGE_FAIL_UNDER: ${{ env.COVERAGE_THRESHOLD }}
        run: |
          echo "::group::Running pytest with coverage"
          # Ensure we're in the correct directory and show structure
          cd ${{ env.PYTHON_ROOT }}
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Current directory: $(pwd)"
          echo "Project root: $(cd .. && pwd)"
          echo "Directory structure:"
          ls -la
          echo "Tests directory structure:"
          ls -la ../tests

          # Run tests from backend directory but point to tests in root
          python -m pytest \
            --cov=app \
            --cov-report=xml:coverage.xml \
            --cov-report=term-missing \
            --junitxml=pytest-report.xml \
            -v \
            ../tests
          echo "::endgroup::"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: |
            ${{ env.PYTHON_ROOT }}/coverage.xml
            ${{ env.PYTHON_ROOT }}/pytest-report.xml
          retention-days: 14

  frontend-lint:
    name: Frontend Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_ROOT }}
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'http://localhost:8000' }}
      REACT_APP_ENVIRONMENT: ${{ env.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.NODE_ROOT }}/package-lock.json

      - name: Install dependencies
        id: install
        run: |
          echo "::group::Install npm dependencies"
          npm ci
          echo "::endgroup::"

      - name: Run ESLint
        if: success() || failure()
        run: |
          echo "::group::Running ESLint"
          npm run lint || echo "::warning::ESLint issues found"
          echo "::endgroup::"

  frontend-test:
    name: Frontend Tests
    needs: frontend-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.NODE_ROOT }}
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'http://localhost:8000' }}
      REACT_APP_ENVIRONMENT: ${{ env.ENVIRONMENT }}
      REACT_APP_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.NODE_ROOT }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        run: |
          echo "::group::Running Jest tests with coverage"
          mkdir -p coverage
          npm run test:ci || echo "::warning::No tests found or tests failed"
          echo "::endgroup::"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: ${{ env.NODE_ROOT }}/coverage
          retention-days: 14
          if-no-files-found: warn

  build:
    name: Build
    needs: [backend-test, frontend-test]
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_API_URL || github.ref == 'refs/heads/develop' && secrets.STAGING_API_URL || 'http://localhost:8000' }}
      REACT_APP_ENVIRONMENT: ${{ env.ENVIRONMENT }}
      REACT_APP_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.NODE_ROOT }}/package-lock.json

      - name: Build frontend
        working-directory: ${{ env.NODE_ROOT }}
        run: |
          echo "::group::Install dependencies"
          npm ci
          echo "::endgroup::"

          echo "::group::Build frontend"
          npm run build
          echo "::endgroup::"

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ${{ env.NODE_ROOT }}/build
          retention-days: 14
