name: CR Validation

on:
  pull_request:
    paths:
    - 'docs/features/*/crs/CR-*.md'

jobs:
  validate-cr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check CR Format
      run: |
        for cr in docs/features/*/crs/CR-*.md; do
          echo "Validating $cr"
          # Add validation logic here
        done

    - name: Check CR Content
      run: |
        for cr in docs/features/*/crs/CR-*.md; do
          echo "Checking content of $cr"
          # Add content checks here
        done
